project:
  type: website

site:
  title: "My Blog"
  navbar:
    left:
      - text: "Project"
        href: posts/Project.ipynb
      - text: "Welcome"
        menu:
          - text: "TEMPO"
            href: welcome/TEMPO.ipynb
          - text: "Artist"
            href: welcome/artist.ipynb
      - text: "Home"
        href: index.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
